services:
  careerpathak-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload during development
      - .:/app
      - /app/node_modules
    environment:
      # These will be overridden by .env file if it exists
      - VITE_GOOGLE_CLIENT_ID=your_google_client_id_here
      - NODE_ENV=development
    stdin_open: true
    tty: true
    networks:
      - careerpathak-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - careerpathak-web
    networks:
      - careerpathak-network
    profiles:
      - production

networks:
  careerpathak-network:
    driver: bridge

volumes:
  node_modules:
